CREATE TABLE [dbo].[tb_lembrete](
	[lem_id] [int] NOT NULL,
	[titulo] [varchar](25) NOT NULL,
	[corpo] [varchar](150) NOT NULL,
 CONSTRAINT [PK_tb_lembrete] PRIMARY KEY CLUSTERED 
(
	[lem_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF